### ISSUE TITLE
Update prerequisites (git, SSH key, ...)

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-cicd-github#12]
Github also allows for instance using the https (which might be simpler to setup)

Secondly, provide link on how to add ssh key or to use https.

**Comment by enibigir** [comment]
This is one of the prerequisites already mentioned in the "Setup" section.
I will update the prerequisites.

**Comment by klieret** [comment]
(I think setup and prerequisites are slightly different: Setup should just be about setting things up, not about learning and understand stuff (that's prerequisites) -- the latter takes potentially more time to complete)
