### ISSUE TITLE
Update episode 02 Title

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-cicd-github#13]
https://hsf-training.github.io/hsf-training-cicd-github/02-enter-sandman/index.html

Current Title: Exit (light) Codes -- what is meant by 'light' here? The word is not used in the episode except in the title.

**Comment by klieret** [comment]
@michmx @enibigir  Do you know more about this?  I can't find anything online about it either (but mostly because it overlaps with other search queries)

**Comment by michmx** [comment]
I couldn't find anything. If no other input, I vote to remove "light" from the title.

**Comment by klieret** [comment]
Agreed!
