### ISSUE TITLE
Docker image "rootproject/root-conda:6.18.04" not found

### ISSUE THREAD

**Issue by enibigir** [hsf-training/hsf-training-cicd-github#22]
May not exist anymore.
To be confirmed.
In the mean time, looking for an alternative working image

**Comment by enibigir** [comment]
Can't find "rootproject/root-conda:6:18.04" image.
Therefore it will be replaced by "rootproject/root:6.22.06-conda"

**Comment by amanmdesai** [comment]
https://github.com/hsf-training/hsf-training-cms-analysis/issues/12

there was a similar discussion above. 

pinging @klieret

**Comment by klieret** [comment]
Thanks for resolving this!
