### ISSUE TITLE
Add explanation on dependabot for gh action version update

### ISSUE THREAD

**Issue by klieret** [hsf-training/hsf-training-cicd-github#41]

**Comment by amanmdesai** [comment]
Hi @klieret  I have two questions:

- Where shall I add this information? 
- Shall I use a separate box for this additional information?
Thanks

**Comment by amanmdesai** [comment]
I feel somewhere in episode 8 which introduces checkout@v3 for the first time would be a nice place to add this information.

**Comment by klieret** [comment]
Exactly! I'd say it could be more than just a box, perhaps a new subsection after the example?
