### ISSUE TITLE
Outdated URL to simplified authentication with the gh command line interface

### ISSUE THREAD

**Issue by krishnakumarg1984** [hsf-training/hsf-training-cicd-github#74]
On https://hsf-training.github.io/hsf-training-cicd-github/ , it says:

>How to interact with remotes in git (if you are not familiar with git, click [here](https://swcarpentry.github.io/git-novice/); for simplified authentication with the gh command line interface, see [this version of the git training](https://mambelli.github.io/git-novice/07-github/index.html))

However, this URL is currently invalid.

**Comment by klieret** [comment]
Thanks for the report @krishnakumarg1984
